/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package operation;

public class Division {
    public int divide(int a, int b) {
	if(b == 0) throw new RuntimeException("divide by zero error");
        return a/b; 
    }
}
