/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package operation;

import org.junit.Test;
import static org.junit.Assert.*;

public class DivisionTest {
    @Test public void testDivision() {
       Division division = new Division();
       assertEquals(3, division.divide(6, 2));
    }
}
